import type { BusinessFlowDefinition } from '../../src/flow-engine';

export const flowDefinitionTemplate = {
  id: 'replace-me',
  caseId: 'XX-001',
  name: '替换为业务名称',
  module: '替换为模块',
  priority: 'P0',
  level: 'L4',
  scope: 'Client+Admin',
  type: 'E2E / Mutation / Money',
  status: 'Pending',
  implemented: false,
  changesData: true,
  affectsMoney: true,
  requiresClient: true,
  requiresAdmin: true,
  requiresThirdParty: false,
  requiresSecurityKey: true,
  supportsResume: true,
  clientAction: '替换为Client动作',
  adminAction: 'Approve',
  command: null,
  npmScript: null,
  safetySwitch: 'ALLOW_MONEY_TESTS',
  safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
  regressionClass: 'Money',
  defaultRegression: false,
  moneyRegression: false,
  realE2EVerified: false,
  orderIdPrefix: null,
  businessResult: 'Not Run',
  automationResult: 'Not Run',
  primaryOracles: [],
  secondaryOracles: [],
  menuSection: '未实现流程',
  menuOrder: 999,
  description: '替换为真实业务规则。'
} satisfies BusinessFlowDefinition;

