import type {
  AdminAction,
  BusinessFlowDefinition,
  BusinessOrderPrefix,
  FlowAutomationResult,
  FlowBusinessResult,
  FlowScope,
  FlowStatus,
  MoneyExecutionProfile,
  RegressionClass,
  TestLevel
} from '../src/flow-engine/definition';

export type {
  AdminAction,
  BusinessFlowDefinition,
  BusinessOrderPrefix,
  FlowAutomationResult,
  FlowBusinessResult,
  FlowScope,
  FlowStatus,
  MoneyExecutionProfile,
  RegressionClass,
  TestLevel
} from '../src/flow-engine/definition';

export type FlowMenuSection = 'Client基础' | '注册' | '兑换' | '资金互转' | '入金' | '出金' | '信托服务' | '运营' | '未实现流程';
export type FlowDefinition = BusinessFlowDefinition & { menuSection: FlowMenuSection };

export type ReportAction = {
  id: string;
  name: string;
  npmScript: string;
  menuOrder: number;
};

export type FlowGroupDefinition = {
  id: string;
  name: string;
  status: FlowStatus;
  flowIds: readonly string[];
  description: string;
};

export type SafeSuiteAction = {
  id: string;
  name: string;
  level: TestLevel | 'L0-L3';
  npmScript: string;
  menuOrder: number;
};

type FlowInput = Omit<
  FlowDefinition,
  | 'command'
  | 'safetySwitches'
  | 'businessResult'
  | 'automationResult'
  | 'primaryOracles'
  | 'secondaryOracles'
  | 'orderIdPrefix'
  | 'level'
  | 'requiresClient'
  | 'requiresSecurityKey'
  | 'supportsResume'
  | 'clientAction'
  | 'adminAction'
  | 'regressionClass'
  | 'capabilityStatus'
> & {
  safetySwitches?: readonly string[];
  businessResult?: FlowBusinessResult;
  automationResult?: FlowAutomationResult;
  primaryOracles?: readonly string[];
  secondaryOracles?: readonly string[];
  orderIdPrefix?: BusinessOrderPrefix | null;
  level?: TestLevel;
  requiresClient?: boolean;
  requiresSecurityKey?: boolean;
  supportsResume?: boolean;
  clientAction?: string;
  adminAction?: AdminAction;
  regressionClass?: RegressionClass;
  moneyExecution?: MoneyExecutionProfile;
  capabilityStatus?: FlowStatus;
};

function inferLevel(input: FlowInput): TestLevel {
  if (input.type.includes('External')) return 'L5';
  if (input.changesData || input.type.includes('Mutation')) return 'L4';
  if (input.type.includes('Dry Run')) return 'L3';
  if (input.type.includes('Validation')) return 'L1';
  if (input.type.includes('Reconciliation') || input.type.includes('Read-only')) return 'L2';
  return 'L0';
}

function regressionClassFor(level: TestLevel): RegressionClass {
  return {
    L0: 'Smoke',
    L1: 'Validation',
    L2: 'Readonly',
    L3: 'Dry Run',
    L4: 'Money',
    L5: 'External Sandbox'
  }[level] as RegressionClass;
}

function inferAdminAction(input: FlowInput): AdminAction {
  if (!input.requiresAdmin) return 'None';
  if (input.id.includes('reject')) return 'Reject';
  if (input.id === 'deposit') return 'Claim';
  if (input.changesData) return 'Approve';
  return 'None';
}

function defineFlow(input: FlowInput): FlowDefinition {
  const level = input.level ?? inferLevel(input);
  return {
    ...input,
    capabilityStatus: input.capabilityStatus ?? input.status,
    level,
    requiresClient: input.requiresClient ?? true,
    requiresSecurityKey: input.requiresSecurityKey ?? false,
    supportsResume: input.supportsResume ?? (input.changesData && input.requiresAdmin),
    clientAction: input.clientAction ?? (input.changesData ? '提交Client业务申请' : '只读页面验证'),
    adminAction: input.adminAction ?? inferAdminAction(input),
    regressionClass: input.regressionClass ?? regressionClassFor(level),
    command: input.npmScript ? `npm run ${input.npmScript}` : null,
    safetySwitches:
      input.safetySwitches ?? (input.safetySwitch ? [input.safetySwitch] : []),
    businessResult: input.businessResult ?? (input.realE2EVerified ? 'Passed' : 'Not Run'),
    automationResult: input.automationResult ?? (input.implemented ? 'Passed' : 'Not Run'),
    primaryOracles: input.primaryOracles ?? [],
    secondaryOracles: input.secondaryOracles ?? [],
    orderIdPrefix: input.orderIdPrefix ?? null
  };
}

export function getFlowDefinition(flowId: string): FlowDefinition {
  const definition = FLOW_REGISTRY.find(flow => flow.id === flowId);
  if (!definition) throw new Error(`Unknown Flow Definition: ${flowId}.`);
  return definition;
}

export function findFlowDefinition(
  identity: string | undefined
): FlowDefinition | undefined {
  if (!identity) return undefined;
  return FLOW_REGISTRY.find(
    flow => flow.id === identity || flow.caseId === identity
  );
}

export const FLOW_REGISTRY: readonly FlowDefinition[] = [
  ...([['BH', '巴林'], ['SG', '新加坡']] as const).flatMap(([country, label]) => [
    defineFlow({
      id: `admin-operations-opening-${country.toLowerCase()}-dry-run`, caseId: `ADMIN-OPEN-${country}-DRY`,
      name: `运营客户${label}开户提交前验证`, module: '运营客户开户', priority: 'P0', scope: 'Admin',
      type: 'Dry Run / Read-only', status: 'Ready', implemented: true, changesData: false, affectsMoney: false,
      requiresClient: false, requiresAdmin: true, requiresThirdParty: false, supportsResume: false,
      adminAction: 'None', clientAction: '无Client操作',
      npmScript: `test:admin:opening:${country.toLowerCase()}:dry-run`, safetySwitch: null,
      defaultRegression: false, moneyRegression: false, realE2EVerified: null,
      businessResult: 'N/A', automationResult: 'Passed', menuSection: '运营', menuOrder: country === 'BH' ? 110 : 112,
      primaryOracles: ['原客户邮箱/UID/类型/启用状态匹配且本地区未开通', '本地区表单真实可填', '最终确认0次且账户仍未开通'],
      description: 'Admin运营 -> 客户；只验证零费用开户表单并取消，不使用Client开户申请或KYC开户审核页面。'
    }),
    defineFlow({
      id: `admin-operations-opening-${country.toLowerCase()}`, caseId: `ADMIN-OPEN-${country}-001`,
      name: `运营客户${label}账户开通`, module: '运营客户开户', priority: 'P0', scope: 'Admin',
      type: 'E2E / Mutation', status: 'Ready', implemented: true, changesData: true, affectsMoney: false,
      requiresClient: false, requiresAdmin: true, requiresThirdParty: false, supportsResume: true,
      adminAction: 'None', clientAction: '无Client操作',
      npmScript: `test:admin:opening:${country.toLowerCase()}`, safetySwitch: 'ALLOW_ADMIN_MUTATION_TESTS',
      defaultRegression: false, moneyRegression: false, realE2EVerified: true,
      businessResult: 'Passed', automationResult: 'Passed', menuSection: '运营', menuOrder: country === 'BH' ? 111 : 113,
      primaryOracles: ['原客户候选唯一且本地区未开通', '开户弹窗客户和地区二次匹配',
        '本Run最终确认最多1次', '重新查询同一客户本地区已开户，账号和收款人与配置一致'],
      description: `2026-09-09 ADMIN-OPEN-${country}-AH-20260909真实通过：原AH客户唯一，费用框保持空白，最终确认1次；重新查询${label}已开户且账户信息一致。原Run已COMPLETED，禁止重跑。独立Admin直接开户，收费分支仍待付款账户和扣费规则确认。`
    })
  ]),
  defineFlow({
    id: 'trust-beneficiary-reconciliation', caseId: 'TRUST-BEN-003', name: '信托受益人提交结果只读复核',
    module: '信托服务', priority: 'P0', scope: 'Client+Admin', type: 'Read-only / Reconciliation', status: 'Ready',
    implemented: true, changesData: false, affectsMoney: false, requiresAdmin: true, requiresThirdParty: false,
    npmScript: 'test:trust:beneficiary:resume-reconciliation', safetySwitch: null,
    defaultRegression: false, moneyRegression: false, realE2EVerified: false,
    businessResult: 'N/A', automationResult: 'Passed', supportsResume: true,
    menuSection: '信托服务', menuOrder: 40,
    primaryOracles: ['同一Personal用户与Trust Number保持一致', 'Client与Admin只读确认受益人是否真实存在'],
    description: '仅复核已经点击过一次提交的原受益人，不创建受益人、不创建银行账户、不执行Admin审核。'
  }),
  defineFlow({
    id: 'trust-beneficiary-golden-journey', caseId: 'TRUST-BEN-002', name: '信托受益人完整闭环',
    module: '信托服务', priority: 'P0', scope: 'Client+Admin', type: 'E2E / Mutation / Resume', status: 'Ready',
    implemented: true, changesData: true, affectsMoney: false, requiresAdmin: true, requiresThirdParty: false,
    npmScript: 'test:trust:beneficiary:client-create', safetySwitch: 'ALLOW_CLIENT_MUTATION_TESTS',
    safetySwitches: ['ALLOW_CLIENT_MUTATION_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false, moneyRegression: false, realE2EVerified: true,
    businessResult: 'Passed', automationResult: 'Passed', supportsResume: true, adminAction: 'Approve',
    clientAction: '在同一现有Personal Trust中创建一个受益人和其银行账户',
    menuSection: '信托服务', menuOrder: 41,
    primaryOracles: [
      '同一现有Personal用户和Trust Number',
      'Client只创建一个唯一受益人并取得真实创建证据',
      '同一受益人只创建一个银行账户且关联正确',
      'Admin信托和受益人候选均严格为1并通过详情复核',
      'Admin受益人审批只执行一次并进入成功终态',
      'Client受益人与银行账户状态和Admin一致'
    ],
    description: 'TBEN-20260908-AH-02已真实验证：同一Personal Trust内创建唯一受益人和银行账户，Admin候选唯一并单次审核通过，Client状态同步；银行账户无独立Admin审核入口。'
  }),
  defineFlow({
    id: 'user-to-user-transfer-preflight', caseId: 'U2U-001', name: '用户间转账只读预检',
    module: '用户间转账', priority: 'P0', scope: 'Client', type: 'Read-only', status: 'In Progress',
    implemented: true, changesData: false, affectsMoney: false, requiresAdmin: false, requiresThirdParty: false,
    npmScript: 'test:client:u2u:preflight', safetySwitch: null, defaultRegression: false,
    moneyRegression: false, realE2EVerified: false, automationResult: 'Not Run', businessResult: 'N/A',
    menuSection: 'Client基础', menuOrder: 30,
    description: '只读确认ENV指定Sender、独立用户转账表单、收款邮箱与资产选项；不提交、不进行安全密钥验证，不进入Admin。'
  }),
  defineFlow({
    id: 'user-to-user-transfer', caseId: 'U2U-002', name: '用户间转账完整闭环',
    module: '用户间转账', priority: 'P0', scope: 'Client+Admin', type: 'Money / Mutation', status: 'In Progress',
    implemented: true, changesData: true, affectsMoney: true, requiresAdmin: true, requiresThirdParty: false,
    requiresSecurityKey: true, supportsResume: true, orderIdPrefix: 'TRF',
    npmScript: 'test:client:u2u', safetySwitch: 'ALLOW_MONEY_TESTS', safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_CLIENT_MUTATION_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    adminAction: 'Approve',
    defaultRegression: false, moneyRegression: true, realE2EVerified: false,
    businessResult: 'Not Run', automationResult: 'Not Run', menuSection: '未实现流程', menuOrder: 30,
    primaryOracles: ['指定Sender认证、KYC和余额充足', '收款用户存在、资格有效且非本人',
      '安全密钥单次验证后真实TRF存在', 'Client真实TXN对应唯一Admin候选，详情匹配并审核通过一次',
      'Admin审核提交成功即流程完成，不再执行余额和双方流水校验'],
    description: '用户间转账以Admin审核提交成功为终点，直接PASS；不自动核验余额或双方流水。原40.11 USD订单已批准，禁止重复转账或批准。'
  }),
  defineFlow({
    id: 'user-to-user-transfer-approve-resume', caseId: 'U2U-002-RESUME', name: '原用户间转账审核提交成功闭环',
    module: '用户间转账', priority: 'P0', scope: 'Client+Admin', type: 'Money / Mutation', status: 'In Progress',
    implemented: true, changesData: true, affectsMoney: true, requiresAdmin: true, requiresThirdParty: false,
    requiresSecurityKey: false, supportsResume: true, orderIdPrefix: 'TRF', adminAction: 'Approve',
    clientAction: '仅确认原发送方身份，禁止新建转账，不验证余额和双方流水',
    npmScript: 'test:client:u2u:approve-resume', safetySwitch: 'ALLOW_ADMIN_MUTATION_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'], defaultRegression: false,
    moneyRegression: true, realE2EVerified: false, menuSection: '未实现流程', menuOrder: 33,
    primaryOracles: ['原Client/Admin TXN唯一匹配并通过详情二次核对', '填写备注后只批准一次且审核提交成功'],
    description: '只Resume既有原订单，审核提交成功后直接COMPLETED和PASS；不执行余额、流水尾部检查，不再要求临时跳过开关。'
  }),
  defineFlow({
    id: 'user-to-user-transfer-admin-review', caseId: 'U2U-004', name: '原用户转账Admin审核入口只读核对',
    module: '用户间转账', priority: 'P0', scope: 'Client+Admin', type: 'Read-only', status: 'In Progress',
    implemented: true, changesData: false, affectsMoney: false, requiresAdmin: true, requiresThirdParty: false,
    npmScript: 'test:client:u2u:admin-review', safetySwitch: null, defaultRegression: false,
    moneyRegression: false, realE2EVerified: false, menuSection: 'Client基础', menuOrder: 32,
    description: '仅查原TRF对应资金互转唯一候选并打开审核详情，不批准、不拒绝、不创建新转账。'
  }),
  defineFlow({
    id: 'user-to-user-transfer-settlement', caseId: 'U2U-005', name: '原用户间转账审核结果只读核查',
    module: '用户间转账', priority: 'P0', scope: 'Client+Admin', type: 'Read-only / Reconciliation', status: 'In Progress',
    implemented: true, changesData: false, affectsMoney: false, requiresAdmin: true, requiresThirdParty: false,
    npmScript: 'test:client:u2u:settlement', safetySwitch: null, defaultRegression: false,
    moneyRegression: false, realE2EVerified: false, menuSection: 'Client基础', menuOrder: 34,
    primaryOracles: ['原TXN唯一且Admin审核提交成功'],
    description: '只读确认原TXN的Admin审核结果即结束，不检查余额和双方流水，不再次批准或创建新订单。'
  }),
  defineFlow({
    id: 'user-to-user-transfer-reconciliation', caseId: 'U2U-003', name: '原用户转账只读复核',
    module: '用户间转账', priority: 'P0', scope: 'Client', type: 'Read-only / Reconciliation', status: 'In Progress',
    implemented: true, changesData: false, affectsMoney: false, requiresAdmin: false, requiresThirdParty: false,
    npmScript: 'test:client:u2u:reconciliation', safetySwitch: null, defaultRegression: false,
    moneyRegression: false, realE2EVerified: false, menuSection: 'Client基础', menuOrder: 31,
    description: '只读取指定Run的原TRF、双方余额和TXN，禁止资金确认、安全密钥验证或Admin操作。'
  }),
  defineFlow({
    id: 'personal-registration',
    caseId: 'REG-P-002',
    name: '个人用户注册完整闭环',
    module: '用户注册',
    priority: 'P0',
    scope: 'Client+Admin+Third Party',
    type: 'E2E / Mutation',
    status: 'Ready',
    implemented: true,
    changesData: true,
    affectsMoney: false,
    requiresAdmin: true,
    requiresThirdParty: true,
    requiresSecurityKey: false,
    supportsResume: true,
    clientAction: '创建一个全新Sandbox个人用户，完成协议签署后单次点击右下角提交',
    adminAction: 'Approve',
    npmScript: 'test:registration:personal',
    safetySwitch: 'ALLOW_CLIENT_MUTATION_TESTS',
    safetySwitches: ['ALLOW_CLIENT_MUTATION_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: false,
    realE2EVerified: true,
    primaryOracles: [
      '注册提交成功且仅提交一次',
      '新用户自动认证成功',
      '个人账户类型选择成功',
      'Documenso完成且Fidere识别签署完成后才允许最终提交',
      '签署完成后右下角提交仅点击一次，member-profile返回成功并进入sign-success',
      '最终提交后在Admin生成唯一KYC案件',
      '个人用户Tab唯一原案件完成全部实际KYC审核阶段',
      '干净登录原Client账号，kyc_status为审核通过且页面可正常使用',
      '未创建第二个用户'
    ],
    secondaryOracles: [
      '个人注册Journey Context已安全生成',
      'Documenso完成前Client最终提交按钮应不可用；提前可用仅产生产品警告'
    ],
    menuSection: '注册',
    menuOrder: 1,
    description: '客户端表单与签署复用原实现；提交后接共享KYC Approval，固定reviewId分阶段防重，最终必须干净登录确认Client KYC通过。新增闭环逻辑需按指定原Run授权验证，不自动重注册。'
  }),
  defineFlow({
    id: 'corporate-registration-validation',
    caseId: 'REG-C-001',
    name: '企业账户注册Validation',
    module: '用户注册',
    priority: 'P0',
    scope: 'Client',
    type: 'Validation / Recon',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    requiresSecurityKey: false,
    supportsResume: true,
    clientAction: '复用Corporate Draft只读验证企业注册步骤和上传契约',
    adminAction: 'None',
    npmScript: 'test:registration:corporate:validation',
    safetySwitch: null,
    defaultRegression: false,
    moneyRegression: false,
    realE2EVerified: false,
    businessResult: 'N/A',
    automationResult: 'Passed',
    primaryOracles: [
      '企业注册9个步骤均可从真实页面识别',
      '运营信息7个公司文件字段与合规问询可选AML文件字段可定位',
      '授权代表自然人文件字段可定位',
      '不执行企业KYC最终提交'
    ],
    secondaryOracles: ['企业签署文档需在授权代表完成后继续独立Dry Run'],
    menuSection: '注册',
    menuOrder: 2,
    description: '使用指定Sandbox Corporate Draft完成真实页面Recon和只读Validation；REG-C-002仍等待测试资产、完整企业资料及企业签署Dry Run。'
  }),
  defineFlow({
    id: 'corporate-registration',
    caseId: 'REG-C-002',
    name: '企业账户注册完整闭环',
    module: '用户注册',
    priority: 'P0',
    scope: 'Client+Admin+Third Party',
    type: 'E2E / Mutation',
    status: 'Ready',
    implemented: true,
    changesData: true,
    affectsMoney: false,
    requiresAdmin: true,
    requiresThirdParty: true,
    requiresSecurityKey: false,
    supportsResume: true,
    clientAction: '完成企业KYB资料、上传、签署并最终提交一次',
    adminAction: 'Approve',
    npmScript: 'test:registration:corporate',
    safetySwitch: 'ALLOW_CLIENT_MUTATION_TESTS',
    safetySwitches: ['ALLOW_CLIENT_MUTATION_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: false,
    realE2EVerified: true,
    primaryOracles: [
      '基本档案、运营信息、资产来源、合规问询和授权代表按真实页面独立完成',
      '只创建一名自然人董事，不创建法人董事',
      '只创建一名自然人股东，不创建企业股东',
      '本次自然人董事/自然人股东Journey适用文件按字段唯一映射并上传成功',
      '企业授权文档真实签署完成',
      '企业KYC最终提交仅一次',
      '企业用户Tab唯一原案件完成实际KYB审核',
      '干净登录同一企业账号，kyb_status为审核通过且页面可正常使用'
    ],
    secondaryOracles: ['Admin Post-Registration Verification仅为非计分Diagnostic'],
    menuSection: '注册',
    menuOrder: 3,
    description: '企业表单、资料及独立Signer保持原实现；等待审核仅表示Client已提交，之后复用参数化Admin KYC闭环，最终验证Client真实KYB通过。'
  }),
  defineFlow({
    id: 'personal-registration-admin-approval',
    caseId: 'REG-P-003',
    name: '个人用户注册Admin审核通过闭环',
    module: '用户注册',
    priority: 'P0',
    scope: 'Client+Admin',
    type: 'E2E / Mutation / Resume',
    status: 'Ready',
    implemented: true,
    changesData: true,
    affectsMoney: false,
    requiresAdmin: true,
    requiresThirdParty: false,
    requiresSecurityKey: false,
    supportsResume: true,
    clientAction: '复用已提交的个人KYC账号，不重新注册、签署或提交',
    adminAction: 'Approve',
    npmScript: 'test:registration:personal:admin-approval:resume',
    safetySwitch: 'ALLOW_ADMIN_MUTATION_TESTS',
    defaultRegression: false,
    moneyRegression: false,
    realE2EVerified: true,
    businessResult: 'Passed',
    automationResult: 'Passed',
    primaryOracles: [
      '复用原Personal账号',
      'Admin候选唯一且详情匹配',
      'Admin审核进入成功终态',
      'Client KYC进入成功终态且账号可继续使用'
    ],
    secondaryOracles: ['非核心Admin展示字段仅作为Diagnostic'],
    menuSection: '注册',
    menuOrder: 5,
    description: '按显式sourceRunId和reviewId Resume原个人案件；info_review和doc_review分别持久化尝试，已完成阶段不再审核。历史Dashboard证据不替代新的Client KYC终态验证。'
  }),
  defineFlow({
    id: 'corporate-registration-admin-approval',
    caseId: 'REG-C-003',
    name: '企业用户注册Admin审核通过闭环',
    module: '用户注册',
    priority: 'P0',
    scope: 'Client+Admin',
    type: 'E2E / Mutation / Resume',
    status: 'Ready',
    implemented: true,
    changesData: true,
    affectsMoney: false,
    requiresAdmin: true,
    requiresThirdParty: false,
    requiresSecurityKey: false,
    supportsResume: true,
    clientAction: '复用已提交的企业KYC账号，不重新上传、签署或提交',
    adminAction: 'Approve',
    npmScript: 'test:registration:corporate:admin-approval:resume',
    safetySwitch: 'ALLOW_ADMIN_MUTATION_TESTS',
    defaultRegression: false,
    moneyRegression: false,
    realE2EVerified: true,
    businessResult: 'Passed',
    automationResult: 'Passed',
    primaryOracles: [
      '复用原Corporate账号和已提交资料',
      'Admin候选严格等于1且详情匹配',
      'Admin Approve仅执行一次并进入成功终态',
      'Client Corporate KYC进入成功终态且账号可继续使用'
    ],
    secondaryOracles: ['非核心Admin展示字段仅作为Diagnostic'],
    menuSection: '注册',
    menuOrder: 6,
    description: '复用与个人相同的KYC Approval引擎，按BUSINESS进入企业用户Tab，解析真实KYB application，审核后干净登录确认Client kyb_status通过。'
  }),
  defineFlow({
    id: 'corporate-registration-upload-dry-run',
    caseId: 'REG-C-DRY-001',
    name: '企业账户注册Upload Dry Run',
    module: '用户注册',
    priority: 'P0',
    scope: 'Client',
    type: 'Dry Run / Upload',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    requiresSecurityKey: false,
    supportsResume: true,
    clientAction: '复用Corporate Draft验证28个真实上传位置并停在最终提交前',
    adminAction: 'None',
    npmScript: 'test:registration:corporate:upload-dry-run',
    safetySwitch: null,
    defaultRegression: false,
    moneyRegression: false,
    realE2EVerified: false,
    businessResult: 'N/A',
    automationResult: 'Passed',
    primaryOracles: ['28个上传位置接受映射PNG', '企业KYC最终提交保持0次'],
    secondaryOracles: ['企业授权签署仅观察入口，不执行签署'],
    menuSection: '注册',
    menuOrder: 4,
    description: 'L3只读边界内验证全分支28个上传控件、资产映射和Live进度；不保存人员档案、不签署、不最终提交。'
  }),
  defineFlow({
    id: 'client-login',
    name: '客户端登录',
    module: '客户端认证',
    priority: 'P0',
    scope: 'Client',
    type: 'Authentication',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    npmScript: 'auth:client',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: true,
    menuSection: 'Client基础',
    menuOrder: 1,
    description: '使用干净上下文自动登录并覆盖生成auth/client.json。'
  }),
  defineFlow({
    id: 'client-smoke',
    name: '客户端Smoke',
    module: '客户端基础',
    priority: 'P0',
    scope: 'Client',
    type: 'Smoke / Read-only',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    npmScript: 'test:client:smoke',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: true,
    menuSection: 'Client基础',
    menuOrder: 2,
    description: '运行客户端P0 Smoke，排除资金和写操作。'
  }),
  defineFlow({
    id: 'client-readonly-regression',
    name: '客户端只读回归',
    module: '客户端基础',
    priority: 'P0/P1',
    scope: 'Client',
    type: 'Regression / Read-only',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    npmScript: 'test:client',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: true,
    menuSection: 'Client基础',
    menuOrder: 3,
    description: '运行所有已实现Client非资金、非Mutation用例。'
  }),
  defineFlow({
    id: 'exchange-validation',
    name: '兑换提交前校验',
    module: '客户端兑换',
    priority: 'P0',
    scope: 'Client',
    type: 'Validation / Read-only',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    npmScript: 'test:client:exchange:validation',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: null,
    orderIdPrefix: 'OTC',
    menuSection: '兑换',
    menuOrder: 4,
    description: '验证真实账户、金额、报价和确认页，在确认兑换前停止。'
  }),
  defineFlow({
    id: 'exchange-security-key-validation',
    name: '兑换安全密钥校验',
    module: '客户端兑换',
    priority: 'P0',
    scope: 'Client',
    type: 'Validation / Non-mutation',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    npmScript: 'test:client:exchange:security-key',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: null,
    orderIdPrefix: 'OTC',
    menuSection: '兑换',
    menuOrder: 5,
    description: '验证安全密钥弹窗与输入结构，不点击安全密钥验证。'
  }),
  defineFlow({
    id: 'exchange-reconciliation',
    name: '兑换历史只读复核',
    module: '客户端兑换',
    priority: 'P0',
    scope: 'Client',
    type: 'Read-only / Reconciliation',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    npmScript: 'test:client:exchange:reconciliation',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: true,
    orderIdPrefix: 'OTC',
    menuSection: '兑换',
    menuOrder: 6,
    description: '从交易流水列表读取TXN编号，并从对应兑换详情读取OTC订单编号及成交字段。'
  }),
  defineFlow({
    id: 'exchange',
    name: '客户端兑换完整闭环',
    module: '客户端兑换',
    priority: 'P0',
    scope: 'Client',
    type: 'Money / Mutation',
    status: 'Ready',
    implemented: true,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: false,
    requiresThirdParty: false,
    npmScript: 'test:client:exchange',
    safetySwitch: 'ALLOW_MONEY_TESTS',
    defaultRegression: false,
    moneyRegression: true,
    realE2EVerified: true,
    orderIdPrefix: 'OTC',
    requiresSecurityKey: true,
    clientAction: '获取报价、确认兑换并完成安全密钥验证',
    adminAction: 'None',
    moneyExecution: {
      account: '数字资产账户 → 香港账户',
      currency: 'USDT_TRC20 → HKD',
      mutation: '即时兑换并改变两侧余额'
    },
    primaryOracles: [
      '安全密钥验证成功',
      '转出和转入余额按成交结果变化',
      '兑换历史状态、币种和金额与本次成交一致',
      'TXN流水编号和OTC兑换订单编号均可从页面读取'
    ],
    secondaryOracles: ['安全脱敏的网络请求元信息', '非核心展示字段'],
    menuSection: '兑换',
    menuOrder: 7,
    description: '真实成交已验证；以列表TXN流水编号和详情OTC订单编号共同完成唯一成交校验。'
  }),
  defineFlow({
    id: 'transfer-validation',
    caseId: 'TR-001',
    name: '资金互转提交前校验',
    module: '客户端资金互转',
    priority: 'P0',
    scope: 'Client',
    type: 'Validation / Read-only',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    npmScript: 'test:client:transfer:validation',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: null,
    orderIdPrefix: 'TRF',
    requiresSecurityKey: true,
    clientAction: '验证资金互转表单并停在安全密钥验证前',
    adminAction: 'None',
    menuSection: '资金互转',
    menuOrder: 10,
    description: 'TR-001已通过：验证双向账户、EUR/USD/HKD、两位小数、Decimal费用和安全密钥弹窗，停在“验证”前。'
  }),
  defineFlow({
    id: 'transfer-reject',
    caseId: 'TR-002',
    name: '资金互转拒绝闭环',
    module: '资金业务',
    priority: 'P0',
    scope: 'Client+Admin',
    type: 'E2E / Mutation / Money',
    status: 'Ready',
    implemented: true,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: false,
    npmScript: 'test:transfer:reject',
    safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: true,
    realE2EVerified: true,
    orderIdPrefix: 'TRF',
    requiresSecurityKey: true,
    clientAction: '提交资金互转申请并完成安全密钥验证',
    adminAction: 'Reject',
    primaryOracles: [
      'Client原TRF创建成功',
      'Admin候选唯一且详情匹配',
      'Admin拒绝且Client原TRF进入拒绝终态',
      '法域账户无不应有的最终扣减'
    ],
    secondaryOracles: ['Client拒绝原因展示', 'Client全局交易流水展示'],
    menuSection: '资金互转',
    menuOrder: 11,
    description: '真实拒绝闭环已验证：Client创建唯一TRF，Admin业务指纹候选唯一并单次拒绝，原TRF进入拒绝终态且法域余额无最终扣减。'
  }),
  defineFlow({
    id: 'transfer-jurisdiction-to-broker',
    caseId: 'TR-003',
    name: '法域账户转券商审核通过',
    module: '资金业务',
    priority: 'P0',
    scope: 'Client+Admin',
    type: 'Money / Mutation',
    status: 'Ready',
    implemented: true,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: false,
    npmScript: 'test:transfer:approve',
    safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: true,
    realE2EVerified: true,
    orderIdPrefix: 'TRF',
    requiresSecurityKey: true,
    clientAction: '提交香港账户到券商账户的资金互转申请',
    adminAction: 'Approve',
    moneyExecution: {
      account: '香港账户 → 老虎证券',
      currency: 'USD',
      mutation: 'Client提交资金互转，Admin审核通过'
    },
    businessResult: 'Passed',
    automationResult: 'Passed With Warning',
    primaryOracles: [
      'Client成功创建原TRF申请',
      'Admin候选唯一',
      'Admin详情匹配正确',
      'Admin最终状态为已批准',
      'Client原TRF最终状态为已完成',
      '香港账户USD余额准确减少requestedAmount',
      '手续费与页面确认一致',
      '实际到账金额与确认页一致'
    ],
    secondaryOracles: [
      'Client全局交易流水出现对应Transfer记录',
      'Client全局流水TXN编号',
      '其他不影响最终资金状态的展示记录'
    ],
    menuSection: '资金互转',
    menuOrder: 12,
    description: '真实审核通过闭环已验证。核心Oracle全部通过；Client全局交易流水未展示对应Transfer记录，作为Secondary Oracle警告，不阻塞Flow Ready。'
  }),
  defineFlow({
    id: 'transfer-broker-to-jurisdiction',
    caseId: 'TR-004',
    name: '券商转法域账户审核通过',
    module: '资金业务',
    priority: 'P1',
    scope: 'Client+Admin',
    type: 'Money / Mutation',
    status: 'Pending',
    implemented: false,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: true,
    npmScript: null,
    safetySwitch: 'ALLOW_MONEY_TESTS',
    defaultRegression: false,
    moneyRegression: false,
    realE2EVerified: false,
    orderIdPrefix: 'TRF',
    requiresSecurityKey: true,
    menuSection: '资金互转',
    menuOrder: 13,
    description: '审核通过后验证法域账户余额增加；券商转出前余额当前无法直接读取。'
  }),
  defineFlow({
    id: 'transfer-roundtrip',
    caseId: 'TR-005',
    name: '双向往返资金闭环',
    module: '资金业务',
    priority: 'P2',
    scope: 'Client+Admin',
    type: 'Money / Mutation / Low-frequency',
    status: 'Pending',
    implemented: false,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: true,
    npmScript: null,
    safetySwitch: 'ALLOW_MONEY_TESTS',
    defaultRegression: false,
    moneyRegression: false,
    realE2EVerified: false,
    orderIdPrefix: 'TRF',
    menuSection: '资金互转',
    menuOrder: 14,
    description: '低频Money E2E；双向均由Admin通过，验证最终法域余额和总手续费，不加入默认回归。'
  }),
  defineFlow({
    id: 'deposit-validation',
    caseId: 'DP-001',
    name: '入金提交前校验',
    module: '客户端入金',
    priority: 'P0',
    scope: 'Client',
    type: 'Validation / Read-only',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    npmScript: 'test:client:deposit:validation',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: null,
    orderIdPrefix: 'TXN',
    menuSection: '入金',
    menuOrder: 15,
    description: 'DP-001验证银行电汇账户/币种矩阵、打款银行、必填字段和金额格式，在提交前停止。'
  }),
  defineFlow({
    id: 'deposit-reconciliation',
    name: '入金历史只读复核',
    module: 'Client + Admin入金',
    priority: 'P0',
    scope: 'Client+Admin',
    type: 'Read-only / Reconciliation / Dry Run',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: true,
    requiresThirdParty: false,
    npmScript: 'test:deposit:reconciliation',
    safetySwitch: null,
    defaultRegression: false,
    moneyRegression: false,
    realE2EVerified: null,
    orderIdPrefix: 'TXN',
    menuSection: '入金',
    menuOrder: 16,
    description: '使用历史待处理记录验证Client历史、Admin候选唯一、认领详情和拒绝入口，不点击最终操作。'
  }),
  defineFlow({
    id: 'deposit-claim-reconciliation',
    caseId: 'DP-003-RECON',
    name: '现有USD入金续跑就绪复核',
    module: 'Client + Admin入金',
    priority: 'P0',
    scope: 'Client+Admin',
    type: 'Read-only / Reconciliation',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: true,
    requiresThirdParty: false,
    npmScript: 'test:deposit:claim:reconciliation',
    safetySwitch: null,
    defaultRegression: false,
    moneyRegression: false,
    realE2EVerified: null,
    orderIdPrefix: 'TXN',
    menuSection: '入金',
    menuOrder: 17,
    description: '只读定位现有11.97 USD入金：Client交易流水候选1条并打开详情，Admin待处理候选1条；状态为DP-003 Resume Ready。'
  }),
  defineFlow({
    id: 'deposit-reject',
    caseId: 'DP-002',
    name: '入金审核拒绝闭环',
    module: 'Client + Admin入金',
    priority: 'P0',
    scope: 'Client+Admin',
    type: 'E2E / Mutation / Money',
    status: 'Ready',
    implemented: true,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: false,
    npmScript: 'test:deposit:reject',
    safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: true,
    realE2EVerified: true,
    orderIdPrefix: 'TXN',
    businessResult: 'Passed',
    automationResult: 'Passed',
    primaryOracles: [
      'Client原TXN入金申请存在',
      'Admin业务指纹候选唯一',
      'Admin拒绝成功',
      'Client原TXN进入拒绝终态',
      '香港账户HKD最终余额等于提交前余额'
    ],
    secondaryOracles: ['Client全局交易流水及TXN展示', '邮件通知', '非核心详情字段'],
    menuSection: '入金',
    menuOrder: 18,
    description: 'DP-002已通过受控真实执行及只读终态复核：Client原TXN rejected、Admin已拒绝、香港账户HKD余额不变，全局流水可读取同一TXN。'
  }),
  defineFlow({
    id: 'deposit-rejection-journey', caseId: 'DP-004', name: '现有用户法币入金拒绝闭环',
    module: 'Client + Admin入金', priority: 'P0', scope: 'Client+Admin', type: 'E2E / Mutation / Money',
    status: 'In Progress', implemented: true, changesData: true, affectsMoney: true,
    requiresAdmin: true, requiresThirdParty: false, requiresSecurityKey: false, supportsResume: true,
    npmScript: 'test:deposit:rejection-journey', safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_CLIENT_MUTATION_TESTS', 'ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false, moneyRegression: true, realE2EVerified: false, orderIdPrefix: 'TXN',
    clientAction: '原有用户和已批准银行地址单次提交法币入金', adminAction: 'Reject',
    primaryOracles: ['原提交真实创建：Client详情TXN或授权Resume核对完整Admin业务指纹', 'Admin候选唯一且详情匹配', 'Admin原申请拒绝终态',
      'Client原申请已拒绝，金额币种与提交窗口一致，原TXN及拒绝原因一致（如展示）', '最终余额等于提交前余额', '没有重复申请'],
    secondaryOracles: [], menuSection: '入金', menuOrder: 18.1,
    description: '独立DP-004，复用已批准用户和地址；命名Run授权、提交/拒绝持久化单次标记；不执行入金通过。'
  }),
  defineFlow({
    id: 'deposit-rejection-preflight', caseId: 'DP-004-PREFLIGHT', name: '入金拒绝闭环提交前预检',
    module: 'Client + Admin入金', priority: 'P0', scope: 'Client+Admin', type: 'Dry Run',
    status: 'Ready', implemented: true, changesData: false, affectsMoney: false,
    requiresAdmin: true, requiresThirdParty: false, requiresSecurityKey: false,
    npmScript: 'test:deposit:rejection:preflight', safetySwitch: null,
    defaultRegression: false, moneyRegression: false, realE2EVerified: null,
    primaryOracles: ['双端认证有效', '原用户KYC及银行地址审核通过', '入金余额和真实表单可读', '待处理冲突数为0'],
    secondaryOracles: [], menuSection: '入金', menuOrder: 18.2,
    description: '所有Mutation开关关闭；只读确认原用户、地址、余额、表单和Admin列表，最终提交前停止。'
  }),
  defineFlow({
    id: 'deposit',
    caseId: 'DP-003',
    name: '香港账户USD入金认领成功闭环',
    module: 'Client + Admin入金',
    priority: 'P0',
    scope: 'Client+Admin',
    type: 'Money / Mutation',
    status: 'Ready',
    capabilityStatus: 'Ready',
    implemented: true,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: false,
    npmScript: 'test:deposit:claim',
    safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: true,
    realE2EVerified: true,
    businessResult: 'Passed',
    automationResult: 'Passed',
    orderIdPrefix: 'TXN',
    clientAction: '提交香港账户USD银行电汇入金申请',
    adminAction: 'Claim',
    moneyExecution: {
      account: '香港账户',
      currency: 'USD',
      mutation: 'Client提交入金，Admin入账认领'
    },
    primaryOracles: [
      'Client原TXN入金申请创建成功',
      'Admin业务指纹候选唯一且认领详情匹配',
      'Admin处理成功且Client原申请进入成功终态',
      '目标法域账户余额增加实际入账金额'
    ],
    secondaryOracles: ['全局交易流水及TXN展示', '邮件通知', '非核心详情字段'],
    menuSection: '入金',
    menuOrder: 19,
    description: 'DP-003已通过现有申请续跑完成：Client TXN、Admin唯一认领、Client终态和USD余额增加均已验证。'
  }),
  defineFlow({
    id: 'withdrawal-validation',
    caseId: 'WD-001',
    name: '出金提交前Validation',
    module: '客户端出金',
    priority: 'P0',
    scope: 'Client',
    type: 'Validation / Non-mutation',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    npmScript: 'test:client:withdrawal:validation',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: null,
    orderIdPrefix: 'TXN',
    menuSection: '出金',
    menuOrder: 20,
    description: '真实Sandbox已通过账户/币种矩阵、金额校验、全部、确认页和6位安全密钥弹窗Validation；安全密钥验证点击0次。'
  }),
  defineFlow({
    id: 'personal-golden-journey-withdrawal',
    caseId: 'PERSONAL-GJ-WD',
    name: '同一Personal Golden Journey出金审核通过',
    module: 'Fresh User Golden Journey',
    priority: 'P0', scope: 'Client+Admin', type: 'E2E / Mutation / Money / Resume',
    status: 'Ready', implemented: true, changesData: true, affectsMoney: true,
    requiresAdmin: true, requiresThirdParty: false,
    npmScript: 'test:journey:personal:withdrawal', safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false, moneyRegression: true, realE2EVerified: true,
    requiresSecurityKey: true, supportsResume: true, orderIdPrefix: 'TXN',
    primaryOracles: ['原用户唯一出金TXN真实存在', 'Admin唯一候选和详情匹配', 'Admin实际审核通过并进入成功终态', '原TXN完成且无重复出金'],
    secondaryOracles: [],
    menuSection: '出金', menuOrder: 25,
    description: '续接原已入金Journey，不创建用户或造余额；唯一定位、详情核对、实际批准及终态为核心，余额差异仅作非计分Diagnostic。'
  }),
  defineFlow({
    id: 'withdrawal-client-submit',
    caseId: 'WD-004',
    name: '客户端法币出金申请创建',
    module: '客户端出金',
    priority: 'P0',
    scope: 'Client',
    type: 'E2E / Mutation / Money',
    status: 'Ready',
    implemented: true,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: false,
    npmScript: 'test:withdrawal:client-submit',
    safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: true,
    realE2EVerified: true,
    businessResult: 'Passed',
    automationResult: 'Passed',
    orderIdPrefix: 'TXN',
    requiresSecurityKey: true,
    supportsResume: true,
    clientAction: '选择转账方式、上传支持性文件并创建一笔Client出金申请',
    adminAction: 'None',
    primaryOracles: [
      '转账方式和支持性文件填写成功',
      '确认转账和安全密钥验证各执行一次',
      'Client产生唯一新增TXN出金申请'
    ],
    secondaryOracles: ['Admin列表展示', '邮件通知'],
    menuSection: '出金',
    menuOrder: 21,
    description: '只创建一笔Client出金申请并停在CLIENT_CREATED，不执行Admin审批。'
  }),
  defineFlow({
    id: 'withdrawal-reject',
    caseId: 'WD-002',
    name: '出金审核拒绝闭环',
    module: 'Client + Admin出金',
    priority: 'P0',
    scope: 'Client+Admin',
    type: 'E2E / Mutation / Money',
    status: 'Ready',
    implemented: true,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: false,
    npmScript: 'test:withdrawal:reject',
    safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: true,
    realE2EVerified: true,
    orderIdPrefix: 'TXN',
    businessResult: 'Passed',
    automationResult: 'Passed',
    requiresSecurityKey: true,
    clientAction: '提交香港账户USD出金申请并完成安全密钥验证',
    adminAction: 'Reject',
    moneyExecution: {
      account: '香港账户',
      currency: 'USD',
      mutation: 'Client提交出金，Admin拒绝并验证余额恢复'
    },
    primaryOracles: [
      'Client原TXN出金申请存在',
      'Admin业务指纹候选唯一且详情匹配',
      'Admin拒绝成功且Client原TXN进入拒绝终态',
      '拒绝后可用余额恢复且不存在永久错误扣减'
    ],
    secondaryOracles: ['全局交易流水', '邮件通知', '非核心详情字段'],
    menuSection: '出金',
    menuOrder: 22,
    description: 'WD-002真实拒绝闭环已验证：Client原TXN、Admin唯一候选、拒绝终态和余额恢复均通过。'
  }),
  defineFlow({
    id: 'withdraw',
    caseId: 'WD-003',
    name: '出金审核通过闭环',
    module: 'Client + Admin出金',
    priority: 'P0',
    scope: 'Client+Admin',
    type: 'E2E / Mutation / Money',
    status: 'Ready',
    capabilityStatus: 'Ready',
    implemented: true,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: false,
    npmScript: null,
    safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: true,
    realE2EVerified: true,
    orderIdPrefix: 'TXN',
    businessResult: 'Passed',
    automationResult: 'Passed',
    requiresSecurityKey: true,
    clientAction: '提交香港账户USD出金申请并完成安全密钥验证',
    adminAction: 'Approve',
    primaryOracles: [
      'Client原TXN出金申请存在',
      'Admin业务指纹候选唯一且详情匹配',
      'Admin批准且Client原TXN进入成功终态',
      '最终余额、手续费和实际出金金额符合真实规则'
    ],
    secondaryOracles: ['全局交易流水', '邮件通知', '非核心详情字段'],
    menuSection: '出金',
    menuOrder: 23,
    description: 'WD-003真实批准闭环已验证；固定Sandbox凭证和已验证审批表单可复用，历史Resume命令不作为新申请入口。'
  }),
  defineFlow({
    id: 'account-opening-us-validation',
    caseId: 'OPEN-US-001',
    name: '美国账户开户Validation',
    module: '客户端美国账户开户',
    priority: 'P0',
    scope: 'Client',
    type: 'Validation / Read-only',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    npmScript: 'test:client:account-opening:us-validation',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: null,
    primaryOracles: ['美国开户入口、五类资料字段和税务表格状态均可读取，最终提交为0次'],
    secondaryOracles: ['非核心页面说明和预计处理时长'],
    menuSection: '未实现流程',
    menuOrder: 23.1,
    description: '使用专用Sandbox开户账号验证美国账户申请能力，不提交开户申请。'
  }),
  defineFlow({
    id: 'account-opening-us-dry-run',
    caseId: 'OPEN-US-DRY',
    name: '美国账户开户与Documenso签署Dry Run',
    module: 'Client + Admin美国账户开户',
    priority: 'P0',
    scope: 'Client+Admin',
    type: 'Dry Run / External / Read-only',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: true,
    requiresThirdParty: true,
    npmScript: 'test:account-opening:us-upload-dry-run',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: null,
    primaryOracles: [
      '五份固定Sandbox资料分别被正确字段接受',
      'Documenso iframe正常加载并以固定TEST Canvas轨迹满足唯一Signature字段',
      '最终Complete按钮可见且可用，Documenso完成、Client提交和Admin审核点击均为0次'
    ],
    secondaryOracles: ['Documenso可选Upload模式、预填日期/认证勾选和Admin历史开户记录'],
    menuSection: '未实现流程',
    menuOrder: 23.2,
    description: '上传固定Sandbox资料，完成Documenso字段级TEST签名，并停在最终Complete和Client提交之前。'
  }),
  defineFlow({
    id: 'account-opening-us-reject',
    caseId: 'OPEN-US-002',
    name: '美国账户开户历史拒绝只读复核',
    module: 'Client + Admin美国账户开户',
    priority: 'P0',
    scope: 'Client+Admin',
    type: 'Reconciliation / Read-only',
    status: 'Pending',
    implemented: false,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: true,
    requiresThirdParty: false,
    level: 'L2',
    npmScript: null,
    safetySwitch: null,
    safetySwitches: [],
    defaultRegression: false,
    moneyRegression: false,
    realE2EVerified: null,
    supportsResume: false,
    clientAction: '只读历史美国开户拒绝记录',
    adminAction: 'None',
    primaryOracles: ['仅复核已有美国开户拒绝终态，不创建申请且不执行平台Reject'],
    secondaryOracles: ['历史拒绝原因和通知展示'],
    menuSection: '未实现流程',
    menuOrder: 23.3,
    description: '美国开户拒绝后Client不能重新申请，因此禁止用专用开户账号执行Reject；仅在未来存在合适历史数据时做只读复核。'
  }),
  defineFlow({
    id: 'account-opening-us-approve',
    caseId: 'OPEN-US-003',
    name: '美国账户开户审核通过闭环',
    module: 'Client + Admin美国账户开户',
    priority: 'P0',
    scope: 'Client+Admin+Third Party',
    type: 'Money / Mutation / External Workflow',
    status: 'Ready',
    capabilityStatus: 'Ready',
    implemented: true,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: true,
    level: 'L5',
    npmScript: 'test:account-opening:us-approve:resume',
    safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: true,
    realE2EVerified: true,
    businessResult: 'Passed',
    automationResult: 'Passed',
    supportsResume: true,
    clientAction: '确认开户费并完成安全密钥验证',
    adminAction: 'Approve',
    primaryOracles: [
      '5份开户资料上传成功',
      'Documenso通过Complete与确认Sign正式完成',
      '开户费金额从真实弹窗读取且付款账户余额充足',
      'Client开户费确认和安全密钥验证各执行一次',
      '实际开户费扣款等于页面金额',
      'Client只创建一条开户申请',
      'Admin候选唯一',
      'Fidere Admin审核通过',
      '申请真实推送Interlace/BaaS',
      'BaaS最终返回成功状态',
      'Client美国账户最终显示已开户',
      '美国账户真实详情可以打开',
      '没有创建第二条开户申请'
    ],
    secondaryOracles: ['通知记录', '预计处理时长展示', '非核心资料展示字段'],
    menuSection: '未实现流程',
    menuOrder: 23.4,
    description: 'OPEN-US-003完整Happy Path能力已真实验证。历史BAAS_FAILED申请属于Specific Run Resume State，不代表Fresh User Flow能力；Golden Journey必须使用本次Journey用户和唯一手机号启动Fresh Happy Path。'
  }),
  defineFlow({
    id: 'account-opening-us-recovery',
    caseId: 'OPEN-US-004',
    name: '美国账户BaaS失败恢复',
    module: 'Client + Admin + Interlace美国账户开户',
    priority: 'P0',
    scope: 'Client+Admin',
    type: 'Recovery / Mutation / External Workflow',
    status: 'Pending',
    implemented: false,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: true,
    level: 'L5',
    npmScript: null,
    safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: true,
    realE2EVerified: false,
    supportsResume: true,
    clientAction: '查询原美国开户申请，不重新签署或提交',
    adminAction: 'Approve',
    primaryOracles: [
      '从BAAS_FAILED恢复原申请',
      '读取真实BaaS失败原因并仅修正允许修正的资料',
      '不重新Documenso签署、不创建第二条申请',
      '原申请最终进入BAAS_APPROVED和Client已开户终态'
    ],
    secondaryOracles: ['第三方处理时长和通知展示'],
    menuSection: '未实现流程',
    menuOrder: 23.5,
    description: '当前OPEN-US-003已提供真实BAAS_FAILED数据，但恢复动作、允许修正字段和重新推送规则尚未实现或验证；不得重新Client申请、签署或扣费。'
  }),
  defineFlow({
    id: 'account-opening-singapore-readonly',
    caseId: 'OPEN-SG-001',
    name: '新加坡账户已开户Readonly',
    module: '客户端新加坡账户开户',
    priority: 'P1',
    scope: 'Client',
    type: 'Reconciliation / Read-only',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    npmScript: 'test:client:account-opening:sg-readonly',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: null,
    primaryOracles: ['账户页和开户选择弹窗均显示新加坡账户已开通且无重复申请动作'],
    secondaryOracles: ['账户说明和历史申请展示'],
    menuSection: '未实现流程',
    menuOrder: 23.6,
    description: '当前专用用户已开通新加坡账户；首次开户仅受测试数据限制。'
  }),
  defineFlow({
    id: 'account-opening-singapore-approve',
    caseId: 'OPEN-SG-002',
    name: '新加坡账户首次开户批准闭环',
    module: 'Client + Admin新加坡账户开户',
    priority: 'P1',
    scope: 'Client+Admin',
    type: 'Mutation / External Workflow',
    status: 'Blocked',
    implemented: false,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: true,
    level: 'L5',
    npmScript: null,
    safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: true,
    realE2EVerified: false,
    supportsResume: true,
    clientAction: '提交新加坡账户开户申请',
    adminAction: 'Approve',
    primaryOracles: ['原申请唯一', 'Fidere审核通过', '第三方成功', 'Client新加坡账户已开户'],
    secondaryOracles: ['通知和预计处理时长'],
    menuSection: '未实现流程',
    menuOrder: 23.7,
    description: '专用开户用户已经开通新加坡账户，无法再次执行首次开户；状态为BLOCKED_TEST_DATA。'
  }),
  defineFlow({
    id: 'account-opening-bahrain-validation',
    caseId: 'OPEN-BH-001',
    name: '巴林账户开户Validation',
    module: '客户端巴林账户开户',
    priority: 'P1',
    scope: 'Client',
    type: 'Validation / Read-only',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    npmScript: 'test:client:account-opening:bh-validation',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: null,
    primaryOracles: ['巴林账户当前可申请、开户费可读、无资料上传且最终提交为0次'],
    secondaryOracles: ['非核心开户说明'],
    menuSection: '未实现流程',
    menuOrder: 23.8,
    description: '当前专用用户尚未开通巴林账户；Validation停在最终提交前。'
  }),
  defineFlow({
    id: 'account-opening-bahrain-dry-run',
    caseId: 'OPEN-BH-DRY',
    name: '巴林账户开户双端Dry Run',
    module: 'Client + Admin巴林账户开户',
    priority: 'P1',
    scope: 'Client+Admin',
    type: 'Dry Run / Read-only',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: true,
    requiresThirdParty: false,
    npmScript: 'test:account-opening:bh-dry-run',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: null,
    primaryOracles: ['Client巴林表单和Admin开户入口可读，Client/Admin最终动作为0次'],
    secondaryOracles: ['历史巴林申请展示'],
    menuSection: '未实现流程',
    menuOrder: 23.9,
    description: '验证巴林开户双端能力，不提交申请或执行审核。'
  }),
  defineFlow({
    id: 'account-opening-bahrain-approve',
    caseId: 'OPEN-BH-003',
    name: '巴林账户开户批准闭环',
    module: 'Client + Admin巴林账户开户',
    priority: 'P1',
    scope: 'Client+Admin+Third Party',
    type: 'Mutation / External Workflow',
    status: 'Mutation Ready',
    implemented: false,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: true,
    level: 'L5',
    npmScript: null,
    safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: true,
    realE2EVerified: false,
    requiresSecurityKey: true,
    supportsResume: true,
    clientAction: '提交巴林账户开户申请',
    adminAction: 'Approve',
    primaryOracles: [
      'Client巴林账户提交前状态为可申请',
      '页面开户费、付款账户和扣费前余额可读且安全密钥只验证一次',
      'Client只创建一条原申请，Admin候选严格唯一且详情匹配',
      'Fidere Admin只Approve一次并进入第三方终态',
      '开户费余额变化符合页面金额',
      'Client巴林账户最终已开户'
    ],
    secondaryOracles: ['通知和预计处理时长'],
    moneyExecution: {
      account: '页面开户费弹窗显示的付款账户',
      currency: 'USD',
      mutation: '确认巴林账户开户费并创建唯一申请'
    },
    menuSection: '未实现流程',
    menuOrder: 24,
    description: '2026-08-31只读复核确认专用用户仍可申请、页面开户费USD 100且无资料上传；Validation与双端Dry Run通过。复用Account Opening候选、Approve、Resume、余额和共享SecurityKeyDialog能力，等待一次显式授权实现并执行真实Happy Path。'
  }),
  defineFlow({
    id: 'admin-manual-fiat-deposit',
    caseId: 'ADMIN-MD-001', name: 'Admin手动入金与Client余额核验', module: '测试余额准备', priority: 'P0',
    scope: 'Client+Admin', type: 'Money / Mutation', status: 'Ready', implemented: true,
    changesData: true, affectsMoney: true, requiresAdmin: true, requiresThirdParty: false,
    requiresSecurityKey: false, supportsResume: true, clientAction: '只读确认原用户及香港USD余额',
    npmScript: 'test:admin:manual-deposit', safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false, moneyRegression: true, realE2EVerified: true,
    businessResult: 'Passed', automationResult: 'Passed',
    primaryOracles: ['邮箱唯一选中原用户与香港USD账户', '授权金额仅提交一次', 'Client余额实际增加授权金额'],
    secondaryOracles: [], menuSection: '入金', menuOrder: 99,
    description: '独立Admin手动入金Fixture；MD001-AH-20260908实际入账1000USD且只读复核通过。最终按钮在二次确认框内；辅助流水查询为Diagnostic，原Run禁止再入金。'
  }),
  defineFlow({
    id: 'admin-manual-fiat-withdrawal-dry-run', caseId: 'ADMIN-MW-DRY', name: 'Admin手动出金提交前Dry Run', module: '管理端手动出金', priority: 'P0',
    scope: 'Client+Admin', type: 'Dry Run / Read-only', status: 'Ready', implemented: true,
    changesData: false, affectsMoney: false, requiresClient: true, requiresAdmin: true, requiresThirdParty: false,
    requiresSecurityKey: false, supportsResume: false, adminAction: 'None', clientAction: '不提交Client出金',
    npmScript: 'test:admin:manual-withdrawal:dry-run', safetySwitch: null,
    defaultRegression: false, moneyRegression: false, realE2EVerified: null,
    primaryOracles: ['Admin认证和真实手动出金表单可用', '原用户邮箱唯一选择', '最终提交前停止'],
    secondaryOracles: [], menuSection: '出金', menuOrder: 98,
    description: '2026-09-08原AH用户真实Dry Run通过；客户/香港USD/银行唯一，确认框匹配，取消后余额907.65 USD未变，最终资金提交0次。独立于Client出金申请。'
  }),
  defineFlow({
    id: 'digital-address-validation', caseId: 'DA-001', name: '数字资产地址提交前校验', module: '数字资产地址', priority: 'P0',
    scope: 'Client', type: 'Validation / Read-only', status: 'Ready', implemented: true,
    changesData: false, affectsMoney: false, requiresClient: true, requiresAdmin: true, requiresThirdParty: false,
    supportsResume: false, adminAction: 'None', clientAction: '头像 -> 设置 -> 地址管理，普通字段校验后取消',
    npmScript: 'test:digital-address:validation', safetySwitch: null, defaultRegression: false, moneyRegression: false,
    realE2EVerified: null, primaryOracles: ['三个必填项前端校验', '币种网络选择与表单填写', '创建、安全验证和审核均为0次'], secondaryOracles: [],
    menuSection: '出金', menuOrder: 100, description: '数字资产地址新增前校验，不注册真实钱包。'
  }),
  defineFlow({
    id: 'digital-address-dry-run', caseId: 'DA-DRY', name: '数字资产地址新增与审核Dry Run', module: '数字资产地址', priority: 'P0',
    scope: 'Client+Admin', type: 'Dry Run / Read-only', status: 'Ready', implemented: true,
    changesData: false, affectsMoney: false, requiresClient: true, requiresAdmin: true, requiresThirdParty: false,
    supportsResume: false, adminAction: 'None', clientAction: '头像 -> 设置 -> 地址管理，最终提交前停止',
    npmScript: 'test:digital-address:dry-run', safetySwitch: null, defaultRegression: false, moneyRegression: false,
    realE2EVerified: null, primaryOracles: ['Client地址表单与Admin审核入口可用', '最终创建及审核零次'], secondaryOracles: [],
    menuSection: '出金', menuOrder: 100, description: '独立的数字资产地址白名单；不新增、不审批、不转出数字资产。'
  }),
  defineFlow({
    id: 'digital-address-approval', caseId: 'DA-002', name: '数字资产地址新增与审核闭环', module: '数字资产地址', priority: 'P0',
    scope: 'Client+Admin', type: 'E2E / Mutation', status: 'Ready', implemented: true,
    changesData: true, affectsMoney: false, requiresClient: true, requiresAdmin: true, requiresThirdParty: false,
    supportsResume: true, adminAction: 'Approve', clientAction: '新增指定Sandbox钱包地址并完成安全密钥验证一次',
    npmScript: 'test:digital-address', safetySwitch: 'ALLOW_CLIENT_MUTATION_TESTS',
    safetySwitches: ['ALLOW_CLIENT_MUTATION_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'], defaultRegression: false, moneyRegression: false,
    realE2EVerified: true, businessResult: 'Passed', automationResult: 'Passed',
    primaryOracles: ['原用户单次新增地址，非资金转出', '用户、地址、币种、网络、标签及原白名单ID唯一匹配',
      'Admin详情复核与单次确认通过', 'Admin原记录已通过且Client同一地址可见并启用'], secondaryOracles: [],
    menuSection: '出金', menuOrder: 101, description: 'DA002-AH-20260909真实闭环通过：AH原用户单次新增、安全验证、Admin唯一审批，Client同一地址可见且启用；不进行资金或链上操作，完成Run禁止重跑。'
  }),
  defineFlow({
    id: 'admin-manual-fiat-withdrawal', caseId: 'ADMIN-MW-001', name: 'Admin普通手动出金', module: '管理端手动出金', priority: 'P0',
    scope: 'Client+Admin', type: 'Money / Mutation', status: 'Ready', implemented: true,
    changesData: true, affectsMoney: true, requiresClient: true, requiresAdmin: true, requiresThirdParty: false,
    requiresSecurityKey: false, supportsResume: true, adminAction: 'None', clientAction: '只读登录和余额快照，不提交Client出金',
    npmScript: 'test:admin:manual-withdrawal', safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false, moneyRegression: true, realE2EVerified: true,
    businessResult: 'Passed', automationResult: 'Passed',
    primaryOracles: ['原用户、香港USD账户和银行唯一且确认摘要匹配', '最终确认手动出金仅一次', '服务端业务响应成功且Admin显示手动出金成功'],
    secondaryOracles: [], menuSection: '出金', menuOrder: 99,
    description: 'MW001-AH-20260908真实通过：原AH香港USD普通手动出金11.03、手续费2.00，最终确认1次；Admin业务提交成功，余额907.65降至894.62。独立于Client出金审批；不执行费用扣除/调账，原Run禁止重跑。'
  }),
  defineFlow({
    id: 'webull-broker-opening-dry-run', caseId: 'OPEN-WEBULL-001', name: '微牛证券双文档开户预检', module: '券商开户', priority: 'P0',
    scope: 'Client', type: 'Dry Run / Read-only', status: 'Ready', implemented: true,
    changesData: false, affectsMoney: false, requiresAdmin: false, requiresThirdParty: false,
    supportsResume: false, adminAction: 'None', clientAction: '读取微牛开户费用及W-8BEN、CRS两个签署入口，最终操作前停止',
    npmScript: 'test:broker-opening:webull:dry-run', safetySwitch: null,
    defaultRegression: false, moneyRegression: false, realE2EVerified: null,
    primaryOracles: ['复用已有用户', '实际费用可读', 'W-8BEN和CRS分别定位', '未完成双文档不得提交', '无签署、扣费或开户提交'],
    secondaryOracles: [], menuSection: '未实现流程', menuOrder: 26,
    description: '2026-09-09原AH真实页面预检通过：香港USD894.62，实际费用100USD，W-8BEN及CRS入口分别唯一，未签署时下一步禁用。不创建文档，不进行最终签署或扣费。'
  }),
  defineFlow({
    id: 'webull-broker-opening-reconciliation', caseId: 'OPEN-WEBULL-RO', name: '微牛原文档签署只读复核', module: '券商开户', priority: 'P0',
    scope: 'Client', type: 'Read-only', status: 'Ready', implemented: true,
    changesData: false, affectsMoney: false, requiresAdmin: false, requiresThirdParty: false,
    supportsResume: true, adminAction: 'None', clientAction: '读取原微牛文档回写与余额，不打开第三方签署或确认费用',
    npmScript: 'test:broker-opening:webull:reconciliation', safetySwitch: null,
    defaultRegression: false, moneyRegression: false, realE2EVerified: null,
    primaryOracles: ['原用户与原Run', '逐文档读取Fidere状态', '只读余额且所有Mutation开关关闭'],
    secondaryOracles: [], menuSection: '未实现流程', menuOrder: 28,
    description: '需BROKER_SOURCE_RUN_ID和BROKER_OPENING_RUN_ID；仅复核原Run。已开户时读取原微牛状态及余额，不再打开申请或签署。'
  }),
  defineFlow({
    id: 'webull-broker-opening', caseId: 'OPEN-WEBULL-003', name: '微牛证券双文档开户与Admin审核', module: '券商开户', priority: 'P0',
    scope: 'Client+Admin+Third Party', type: 'Money / Mutation', status: 'Ready', implemented: true,
    changesData: true, affectsMoney: true, requiresAdmin: true, requiresThirdParty: true,
    requiresSecurityKey: true, supportsResume: true, adminAction: 'Approve',
    clientAction: '恢复原W-8BEN及CRS签署结果，再确认费用和安全验证；不重复签署', npmScript: 'test:broker-opening:webull:resume',
    safetySwitch: 'ALLOW_MONEY_TESTS', safetySwitches: ['ALLOW_CLIENT_MUTATION_TESTS', 'ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false, moneyRegression: true, realE2EVerified: true,
    businessResult: 'Passed', automationResult: 'Passed',
    primaryOracles: ['原用户与独立微牛申请', '实际开户费及付款账户余额足够；不足先完成授权入金',
      'W-8BEN和CRS各自签署完成，剩余字段0，Fidere逐份确认', 'SecurityKey验证一次且真实创建申请',
      'Admin原微牛申请唯一且详情匹配', 'Admin最终通过一次', 'Client原微牛账户已开通'],
    secondaryOracles: ['开户费流水展示'], menuSection: '未实现流程', menuOrder: 27,
    description: 'OPEN-WEBULL-AH-20260909真实PASS：原AH两份文档通过init-sign返回signed=true恢复，无重签；微牛申请30，Client确认/安全验证/Admin确认通过各1次，候选唯一，Admin已开户、Client已开通。香港USD894.62降至794.62，费用100USD。原Run已COMPLETED，禁止重跑。'
  }),
  defineFlow({
    id: 'tiger-broker-opening', caseId: 'OPEN-TIGER-003', name: '老虎证券开户与Admin审核', module: '券商开户', priority: 'P0',
    scope: 'Client+Admin', type: 'Money / Mutation', status: 'Ready', implemented: true,
    changesData: true, affectsMoney: true, requiresAdmin: true, requiresThirdParty: false,
    requiresSecurityKey: true, supportsResume: true, adminAction: 'Approve',
    clientAction: '老虎证券确认缴费并安全验证一次', npmScript: 'test:broker-opening:tiger',
    safetySwitch: 'ALLOW_MONEY_TESTS', safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false, moneyRegression: true, realE2EVerified: true,
    businessResult: 'Passed', automationResult: 'Passed',
    primaryOracles: ['原Journey单次老虎开户申请', '安全密钥验证一次', 'Admin邮箱与券商时间唯一匹配且详情一致', 'Admin审核通过一次', 'Client原老虎账户已开通'],
    secondaryOracles: [], menuSection: '未实现流程', menuOrder: 25,
    description: 'OPEN-TIGER-AH-20260908真实完成：原AH申请29，开户费100USD，安全验证1次，Admin最终确认通过1次，Client已开通。保存处理结果仅打开确认框，最终需测试券商账号与开户时间；不重复开户。'
  }),
  defineFlow({
    id: 'account-opening-validation',
    caseId: 'OPEN-001',
    name: '开户目录与申请资格Validation',
    module: '客户端开户',
    priority: 'P0',
    scope: 'Client',
    type: 'Validation / Read-only',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    npmScript: 'test:client:account-opening:validation',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: null,
    primaryOracles: ['真实券商目录、账户类型、开户费和当前申请资格均可读取'],
    secondaryOracles: ['可投市场展示', '非核心券商说明'],
    menuSection: '未实现流程',
    menuOrder: 23,
    description: 'OPEN-001只读检查开户目录；不会点击立即开户或创建申请。'
  }),
  defineFlow({
    id: 'account-opening-dry-run',
    caseId: 'OPEN-DRY',
    name: '开户双端Readiness Dry Run',
    module: 'Client + Admin开户',
    priority: 'P0',
    scope: 'Client+Admin',
    type: 'Dry Run / Read-only',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: true,
    requiresThirdParty: false,
    npmScript: 'test:account-opening:dry-run',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: null,
    primaryOracles: ['Client申请资格与Admin审核入口可读，Resume停在PREPARED且写操作为0'],
    secondaryOracles: ['历史开户记录展示'],
    menuSection: '未实现流程',
    menuOrder: 24,
    description: '验证双端入口、候选结构和Resume门禁；当前账号无可申请券商时记录BLOCKED_TEST_DATA。'
  }),
  defineFlow({
    id: 'account-opening',
    name: '开户',
    module: '账户业务',
    priority: 'P0/P1',
    scope: 'Client+Admin',
    type: 'Mutation / External Workflow',
    status: 'Blocked',
    implemented: false,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: true,
    level: 'L5',
    clientAction: '提交账户开户申请',
    adminAction: 'Approve',
    npmScript: null,
    safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: false,
    realE2EVerified: false,
    primaryOracles: [
      'Client唯一开户申请存在',
      'Admin候选唯一且申请资料匹配',
      'Admin终态与Client账户状态一致',
      '第三方渠道终态和开户费变化符合真实规则'
    ],
    secondaryOracles: ['通知记录', '预计处理时长展示', '非核心详情字段'],
    menuSection: '未实现流程',
    menuOrder: 25,
    description: '当前账号三个券商均已开通，缺少可重置未开户账号；真实闭环还依赖券商Sandbox终态。'
  }),
  defineFlow({
    id: 'wealth-subscribe-validation',
    caseId: 'WS-001',
    name: '理财认购提交前Validation',
    module: '客户端理财认购',
    priority: 'P1',
    scope: 'Client',
    type: 'Validation / Read-only',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    npmScript: 'test:client:wealth-subscribe:validation',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: null,
    primaryOracles: ['产品、最低金额、付款账户余额、协议和未提交确认摘要可读取'],
    secondaryOracles: ['年化收益率', '风险等级', '锁定期展示'],
    menuSection: '未实现流程',
    menuOrder: 26,
    description: 'WS-001覆盖真实认购表单校验；确认并提交点击次数保持0。'
  }),
  defineFlow({
    id: 'wealth-subscribe-dry-run',
    caseId: 'WS-DRY',
    name: '理财认购双端Readiness Dry Run',
    module: 'Client + Admin理财认购',
    priority: 'P1',
    scope: 'Client+Admin',
    type: 'Dry Run / Read-only',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: true,
    requiresThirdParty: false,
    npmScript: 'test:wealth-subscribe:dry-run',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: null,
    orderIdPrefix: 'INV',
    primaryOracles: ['Client历史INV可读，Admin三个状态Tab可精确搜索且双方写操作为0'],
    secondaryOracles: ['Admin操作按钮可见性', '非核心产品详情字段'],
    menuSection: '未实现流程',
    menuOrder: 27,
    description: '以Client历史INV在Admin三个状态Tab精确查询；已验证唯一候选、恢复候选所属Tab并打开同一INV详情，写操作保持0次。'
  }),
  defineFlow({
    id: 'wealth-subscribe-reject',
    caseId: 'WS-002',
    name: '理财认购审核拒绝闭环',
    module: 'Client + Admin理财认购',
    priority: 'P1',
    scope: 'Client+Admin',
    type: 'Money / Mutation',
    status: 'Ready',
    implemented: true,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: false,
    requiresSecurityKey: true,
    level: 'L4',
    clientAction: '提交唯一INV认购订单并完成安全密钥验证',
    adminAction: 'Reject',
    npmScript: 'test:wealth:subscribe:reject',
    safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: true,
    realE2EVerified: true,
    businessResult: 'Passed',
    automationResult: 'Passed',
    orderIdPrefix: 'INV',
    primaryOracles: [
      'Client唯一INV认购订单存在',
      'Admin按INV唯一定位且详情匹配',
      'Admin拒绝一次后Client原INV进入拒绝终态',
      '可用、冻结与总余额分别恢复提交前状态，不继续占用资金',
      '被拒绝认购不增加有效持仓数量或持有本金',
      'Client展示拒绝原因时与本次Admin原因一致，且无重复认购'
    ],
    secondaryOracles: ['通知记录'],
    menuSection: '未实现流程',
    menuOrder: 27.1,
    description: '2026-09-09 WS002-20260909-173401真实PASS：香港账户认购Galaxy Digital Lending 1.60 USD，安全验证和Admin确认拒绝各一次，INV唯一且双方已拒绝，可用/冻结/总资金恢复，原本金1.43 USD及有效持仓数不变。默认回归排除，不重跑；WS-003批准用例保持独立。'
  }),
  defineFlow({
    id: 'wealth-subscribe-approve',
    caseId: 'WS-003',
    name: '理财认购审核通过闭环',
    module: 'Client + Admin理财认购',
    priority: 'P1',
    scope: 'Client+Admin',
    type: 'Money / Mutation',
    status: 'Ready',
    implemented: true,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: false,
    requiresSecurityKey: true,
    level: 'L4',
    clientAction: '提交唯一INV认购订单并完成安全密钥验证',
    adminAction: 'Approve',
    npmScript: 'test:wealth:subscribe:approve',
    safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: true,
    realE2EVerified: true,
    businessResult: 'Passed',
    automationResult: 'Passed',
    orderIdPrefix: 'INV',
    primaryOracles: [
      'Client唯一INV认购订单存在',
      'Admin候选唯一且产品、金额和付款账户匹配',
      'Admin批准一次后Client原INV进入成功终态',
      '付款账户余额减少值与页面金额和手续费一致',
      'Client持仓增加可直接观测'
    ],
    secondaryOracles: ['通知记录', '收益展示', '非核心产品详情字段'],
    menuSection: '未实现流程',
    menuOrder: 27.2,
    description: '2026-09-08 WS003-20260908-143500真实通过：香港账户认购1.43 USD，密钥验证和Admin批准各一次，INV唯一、Client持有中、持仓增加及冻结转扣款均验证通过。默认回归不执行；赎回独立暂停。'
  }),
  defineFlow({
    id: 'wealth-subscribe',
    name: '理财认购',
    module: '理财业务',
    priority: 'P1',
    scope: 'Client+Admin',
    type: 'Money / Mutation / External Workflow',
    status: 'Blocked',
    implemented: false,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: true,
    level: 'L5',
    requiresSecurityKey: true,
    clientAction: '提交理财认购订单',
    adminAction: 'Approve',
    npmScript: null,
    safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: false,
    realE2EVerified: false,
    orderIdPrefix: 'INV',
    primaryOracles: [
      'Client唯一INV认购订单存在',
      'Admin候选唯一且产品、金额和付款账户匹配',
      'Client订单终态和付款余额变化一致',
      'Client持仓增加可直接观测'
    ],
    secondaryOracles: ['通知记录', '收益展示', '非核心产品详情字段'],
    menuSection: '未实现流程',
    menuOrder: 28,
    description: '表单、Client历史INV及Admin同一INV精确关联可用，但终态订单无法验证批准/拒绝表单，我的投资未渲染持仓，且没有重置能力。'
  }),
  defineFlow({
    id: 'wealth-redeem-validation',
    caseId: 'WR-001',
    name: '理财赎回资格Validation',
    module: '客户端理财赎回',
    priority: 'P1',
    scope: 'Client',
    type: 'Validation / Read-only',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: false,
    requiresThirdParty: false,
    npmScript: 'test:client:wealth-redeem:validation',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: null,
    orderIdPrefix: 'INV',
    primaryOracles: ['页面真实持仓和赎回动作数量可读，不伪造可赎回资格'],
    secondaryOracles: ['历史赎回记录展示'],
    menuSection: '未实现流程',
    menuOrder: 29,
    description: 'WR-001稳定识别当前缺少可赎回持仓并登记BLOCKED_TEST_DATA。'
  }),
  defineFlow({
    id: 'wealth-redeem-dry-run',
    caseId: 'WR-DRY',
    name: '理财赎回双端Readiness Dry Run',
    module: 'Client + Admin理财赎回',
    priority: 'P1',
    scope: 'Client+Admin',
    type: 'Dry Run / Read-only',
    status: 'Ready',
    implemented: true,
    changesData: false,
    affectsMoney: false,
    requiresAdmin: true,
    requiresThirdParty: false,
    npmScript: 'test:wealth-redeem:dry-run',
    safetySwitch: null,
    defaultRegression: true,
    moneyRegression: false,
    realE2EVerified: null,
    orderIdPrefix: 'INV',
    primaryOracles: ['Client持仓门禁、Admin赎回入口和PREPARED Resume可读且写操作为0'],
    secondaryOracles: ['历史赎回记录展示'],
    menuSection: '未实现流程',
    menuOrder: 30,
    description: '无可赎回持仓时在表单前停止；不创建赎回订单或执行Admin处理。'
  }),
  defineFlow({
    id: 'wealth-redeem',
    name: '理财赎回',
    module: '理财业务',
    priority: 'P1',
    scope: 'Client+Admin',
    type: 'Money / Mutation / External Workflow',
    status: 'Blocked',
    implemented: false,
    changesData: true,
    affectsMoney: true,
    requiresAdmin: true,
    requiresThirdParty: true,
    level: 'L5',
    requiresSecurityKey: true,
    clientAction: '提交理财赎回订单',
    adminAction: 'Approve',
    npmScript: null,
    safetySwitch: 'ALLOW_MONEY_TESTS',
    safetySwitches: ['ALLOW_MONEY_TESTS', 'ALLOW_ADMIN_MUTATION_TESTS'],
    defaultRegression: false,
    moneyRegression: false,
    realE2EVerified: false,
    orderIdPrefix: 'INV',
    primaryOracles: [
      'Client唯一INV赎回订单存在',
      'Admin候选唯一且产品、份额和结算账户匹配',
      'Client订单终态、持仓减少和结算余额增加一致'
    ],
    secondaryOracles: ['通知记录', '预计到账日期展示', '非核心产品详情字段'],
    menuSection: '未实现流程',
    menuOrder: 31,
    description: '当前账号没有页面可见且处于赎回窗口的持仓；禁止伪造测试数据或执行真实赎回。'
  })
] as const;

export const FLOW_GROUP_REGISTRY: readonly FlowGroupDefinition[] = [
  {
    id: 'trust-beneficiary',
    name: '信托受益人',
    status: 'Ready',
    flowIds: ['trust-beneficiary-reconciliation', 'trust-beneficiary-golden-journey'],
    description: 'TRUST-BEN-002已完成真实Client+Admin闭环；历史AA未确认Run保持锁定，已验证AB Run不改写该历史结果。'
  },
  {
    id: 'transfer',
    name: '资金互转',
    status: 'Ready',
    flowIds: [
      'transfer-validation',
      'transfer-reject',
      'transfer-jurisdiction-to-broker'
    ],
    description: 'TR-001、TR-002和TR-003均Ready；TR-003的Client全局流水缺失作为Secondary Oracle警告单独跟踪。'
  },
  {
    id: 'deposit',
    name: '入金',
    status: 'Ready',
    flowIds: [
      'deposit-validation',
      'deposit-reconciliation',
      'deposit-claim-reconciliation',
      'deposit-reject',
      'deposit'
    ],
    description: 'DP-001、DP-002和DP-003均已完成；历史只读复核继续作为L2覆盖。'
  },
  {
    id: 'withdrawal',
    name: '出金',
    status: 'Ready',
    flowIds: ['withdrawal-validation', 'withdrawal-reject', 'withdraw'],
    description: 'WD-001、WD-002和WD-003均已真实验证；资金E2E仍不进入默认回归。'
  },
  {
    id: 'account-opening',
    name: '开户',
    status: 'In Progress',
    flowIds: [
      'account-opening-us-approve',
      'account-opening-bahrain-validation',
      'account-opening-bahrain-dry-run',
      'account-opening-bahrain-approve',
      'account-opening-singapore-approve',
      'account-opening-validation',
      'account-opening-dry-run',
      'account-opening'
    ],
    description: 'OPEN-US-003 Fresh Happy Path能力为Ready，历史BAAS_FAILED仅属于Specific Run Resume；OPEN-BH-003为Mutation Ready但尚未实现真实命令；新加坡首次开户和券商开户仍受不可重置测试数据限制。'
  },
  {
    id: 'wealth-subscribe',
    name: '理财认购',
    status: 'Blocked',
    flowIds: [
      'wealth-subscribe-validation',
      'wealth-subscribe-dry-run',
      'wealth-subscribe-reject',
      'wealth-subscribe-approve',
      'wealth-subscribe'
    ],
    description: 'WS-001与双端历史INV Dry Run已实现且同一INV可精确关联；WS-002/003仍因终态历史记录无法验证最终操作表单、余额规则/持仓Oracle和缺少重置能力而未达到Mutation Ready。'
  },
  {
    id: 'wealth-redeem',
    name: '理财赎回',
    status: 'Blocked',
    flowIds: ['wealth-redeem-validation', 'wealth-redeem-dry-run', 'wealth-redeem'],
    description: 'WR-001与双端入口Dry Run已实现；当前账号没有页面可见且处于赎回窗口的持仓。'
  }
] as const;

export const REPORT_ACTIONS: readonly ReportAction[] = [
  {
    id: 'business-report',
    name: '打开中文业务报告',
    npmScript: 'report:business',
    menuOrder: 8
  },
  {
    id: 'playwright-report',
    name: '打开Playwright技术报告',
    npmScript: 'report:playwright:open',
    menuOrder: 10
  },
  {
    id: 'history-report',
    name: '打开自动化测试历史',
    npmScript: 'report:history',
    menuOrder: 9
  }
] as const;

export const SAFE_SUITE_ACTIONS: readonly SafeSuiteAction[] = [
  { id: 'smoke', name: 'Smoke', level: 'L0', npmScript: 'test:smoke', menuOrder: 1 },
  {
    id: 'validation',
    name: 'Validation',
    level: 'L1',
    npmScript: 'test:validation',
    menuOrder: 2
  },
  {
    id: 'readonly',
    name: 'Readonly',
    level: 'L2',
    npmScript: 'test:readonly',
    menuOrder: 3
  },
  {
    id: 'dry-run',
    name: 'Dry Run',
    level: 'L3',
    npmScript: 'test:dry-run',
    menuOrder: 4
  },
  {
    id: 'p0-safe-regression',
    name: 'P0安全回归',
    level: 'L0-L3',
    npmScript: 'regression',
    menuOrder: 5
  }
] as const;

export const MONEY_MENU_FLOW_IDS = [
  'exchange',
  'transfer-jurisdiction-to-broker',
  'deposit',
  'withdrawal-reject'
] as const;
