const blockedFieldPattern = /(?:password|pwd|otp|captcha|securitykey|token|cookie|authorization|secret|privatekey|idnumber|bankaccount|iban|email|phone)/i;

const allowedBusinessFields = new Set([
  'digitalAddressName', 'digitalAddressAsset', 'digitalAddressNetwork', 'digitalWalletMasked',
  'digitalWhitelistReference', 'digitalAddressCandidateCount', 'digitalAddressAdminBefore',
  'digitalAddressAdminAfter', 'digitalAddressClientStatus', 'digitalAddressSubmissionCount',
  'digitalAddressVerificationCount', 'digitalAddressApprovalCount',
  'purchaseAccount', 'settlementAccount', 'subscriptionOrderId', 'redemptionOrderId', 'holdingOrderId',
  'wealthClientStatus', 'wealthAdminStatus', 'wealthProductId', 'wealthBalanceSnapshots',
  'wealthRejectionReason', 'wealthHoldingEvidence',
  'sourceRunId',
  'candidateStages',
  'registrationUser',
  'registrationReviewId',
  'registrationUserId',
  'registrationKycApprovalAttempts',
  'adminKycTab',
  'adminKycApprovalRequest',
  'adminApprovalUiResult',
  'repeatedSigning',
  'repeatedClientSubmission',
  'environment',
  'accountType',
  'sourceAccountType',
  'targetAccountType',
  'exchangePair',
  'fromCurrency',
  'toCurrency',
  'amount',
  'sourceAmount',
  'sourceBalanceBefore',
  'sourceBalanceAfter',
  'targetBalanceBefore',
  'targetBalanceAfter',
  'rate',
  'fee',
  'expectedReceivedAmount',
  'actualReceivedAmount',
  'ledgerTransactionId',
  'senderLedgerTransactionId',
  'recipientLedgerTransactionId',
  'senderIdentity',
  'recipientIdentity',
  'exchangeOrderId',
  'exchangeCreatedAt',
  'exchangeCompletedAt',
  'transferDirection',
  'transferCurrency',
  'supportedCurrencies',
  'transferAmount',
  'transferSourceBalanceBefore',
  'transferSourceBalanceAfter',
  'transferTargetBalanceBefore',
  'transferTargetBalanceAfter',
  'clientTransferId',
  'transferOrderId',
  'depositOrderId',
  'systemTransactionId',
  'wireReferenceId',
  'depositCurrency',
  'depositAmount',
  'originalDepositAmount',
  'actualDepositAmount',
  'actualBalanceIncrease',
  'balanceOracle',
  'depositChannel',
  'depositPurpose',
  'depositSourceOfFunds',
  'depositBalanceBefore',
  'depositBalanceAfter',
  'depositBalanceCurrent',
  'clientDepositStatus',
  'adminDepositStatus',
  'clientDepositHistoryCandidateCount',
  'clientDetailTransactionNumber',
  'existingDepositResume',
  'noNewDepositCreated',
  'payingBankOptionCount',
  'adminReference',
  'claimConfirmationClicks',
  'rejectConfirmationClicks',
  'withdrawalOrderId',
  'withdrawalCurrency',
  'requestedAmount',
  'feeAmount',
  'expectedNetAmount',
  'actualDebitAmount',
  'beneficiaryAccountSuffix',
  'withdrawalPurpose',
  'withdrawalTransferMethod',
  'supportingDocument',
  'createdOrderCount',
  'adminMutationClicks',
  'preSubmitAdminCandidateCount',
  'preSubmitAdminCandidateStages',
  'safePostSubmitNetworkMetadata',
  'safeToRerun',
  'beforeAvailableBalance',
  'beforeTotalBalance',
  'submittedAvailableBalance',
  'submittedTotalBalance',
  'afterRejectedAvailableBalance',
  'afterRejectedTotalBalance',
  'afterApprovedAvailableBalance',
  'afterApprovedTotalBalance',
  'frozenAmount',
  'releasedAmount',
  'clientWithdrawalStatus',
  'adminWithdrawalStatus',
  'clientWithdrawalCandidateCount',
  'clientCandidateStageCounts',
  'approvalClicks',
  'allWithdrawalAmount',
  'displayedLimits',
  'overBalanceAmount',
  'overBalanceFormBehavior',
  'overBalanceFeeText',
  'securityInputCount',
  'safeRequestEvidence',
  'adminStatusOptions',
  'historicalRejectedCount',
  'afterRejectedAvailableBalanceOracle',
  'historicalCompletedCount',
  'currentPendingActionableCount',
  'approvalRequiredFields',
  'thirdPartyDependency',
  'availablePaymentChannels',
  'availablePaymentBanks',
  'selectedPaymentChannel',
  'selectedPaymentBank',
  'paymentProofFileName',
  'paymentProofType',
  'paymentProofSizeBytes',
  'paymentProofUploaded',
  'approvalNoteFilled',
  'requiredApprovalFieldsSatisfied',
  'approvalButtonEnabled',
  'mutationPerformed',
  'investmentOrderId',
  'openingBrokerCount',
  'openingAvailableBrokerCount',
  'openingAccountTypes',
  'openingFees',
  'openingDocumentUploads',
  'taxFormStatus',
  'signingProvider',
  'signingOpeningMode',
  'signingMethod',
  'signatureUploadAvailable',
  'typedSignatureAvailable',
  'initialsRequired',
  'dateHandling',
  'checkboxHandling',
  'identityChallengePresent',
  'signingRequiredFieldsBefore',
  'signingRequiredFieldsAfter',
  'signingFinalAction',
  'signingFinalActionLocator',
  'signingFieldApplyClicks',
  'signingFinalClicks',
  'finalSubmissionClicks',
  'adminOpeningRowCount',
  'adminOpeningMatchedHistoryCount',
  'usOpeningStatusBefore',
  'openingDocumentAssetCount',
  'documensoCompleteClicks',
  'documensoSigningConfirmationClicks',
  'signingPromptTitle',
  'documensoNetworkStatus',
  'existingUsOpeningApplicationCount',
  'usOpeningChannel',
  'usOpeningChannelEnabled',
  'signingFinalRequestPath',
  'signingFinalHttpStatus',
  'clientSubmissionEvidence',
  'clientSubmittedAt',
  'clientOpeningReference',
  'adminOpeningReference',
  'adminOpeningDetailVerified',
  'adminOpeningUploadedDocumentCount',
  'adminFatcaDocumentAvailable',
  'adminOpeningApprovalClicks',
  'adminApprovalRequestPath',
  'adminApprovalHttpStatus',
  'fidereStatusAfter',
  'baasSubmissionConfirmed',
  'baasFinalStatus',
  'baasFailureReason',
  'clientUsAccountFinalStatus',
  'recoveryRequired',
  'resumeStage',
  'noSecondOpeningApplication',
  'usAccountOverviewRoute',
  'resumeMode',
  'resumeStartStage',
  'documentsUploaded',
  'signatureFieldsCompleted',
  'signatureValue',
  'signerFullNamePresent',
  'fidereModuleName',
  'documensoDocumentTitlePresent',
  'fieldsRemaining',
  'documensoCompleted',
  'clientSubmitted',
  'clientApplicationReference',
  'clientApplicationReferenceSource',
  'adminApproved',
  'noRepeatedDocumentSigning',
  'documentContext',
  'openingFeeCurrency',
  'openingFeeAmount',
  'openingFeePaymentAccount',
  'openingFeeBalanceAccountType',
  'feeBalanceBefore',
  'feeBalanceAfter',
  'observedFeeDebit',
  'feeBalanceSufficient',
  'feeConfirmationButtonText',
  'openingFeeDescription',
  'openFeeConfirmationCount',
  'feeConfirmationClickCount',
  'securityVerificationStatus',
  'applicationCreateCount',
  'applicationCreatedAfterFee',
  'nextClientState',
  'productCount',
  'selectedProduct',
  'minimumInvestment',
  'maximumInvestment',
  'paymentAccount',
  'paymentBalance',
  'wealthHistoryCount',
  'positionRecordCount',
  'redeemablePositionCount',
  'readinessStatus',
  'blockerReason',
  'trustNumber',
  'beneficiaryName',
  'beneficiaryRelationship',
  'beneficiaryPercentage',
  'beneficiaryIdSuffix',
  'beneficiaryStatus',
  'bankAccountSuffix',
  'bankName',
  'bankCurrency',
  'bankAccountStatus',
  'clientCreateCount',
  'beneficiaryConfirmationClickCount',
  'securityDialogObserved',
  'bankAccountCreateCount',
  'bankAccountConfirmationClickCount',
  'bankSecurityVerificationClicks',
  'beneficiaryApproveCount',
  'bankAccountApproveCount',
  'clientMutationResponseCount',
  'clientBeneficiaryRecordObserved',
  'adminBeneficiaryRecordObserved',
  'adminBeneficiaryCount',
  'noDuplicateBeneficiaryCreated',
  'bankApprovalIndependent',
  'adminTransactionId',
  'runId',
  'amountPrecision',
  'candidateCount',
  'candidateStageCounts',
  'normalizedAdminTransfer',
  'customerMatchStrategy',
  'timeWindowApplied',
  'detailVerified',
  'fingerprintFields',
  'rejectReason',
  'claimRemark',
  'jurisdictionBalanceBefore',
  'jurisdictionBalanceAfter',
  'jurisdictionBalanceCurrent',
  'brokerBalanceOracle',
  'targetBrokerBalanceOracle',
  'proposedTransferAmount',
  'displayedFee',
  'displayedExpectedReceivedAmount',
  'expectedJurisdictionBalanceAfterApproval',
  'sourceBalanceRule',
  'historicalClientTransferId',
  'historicalTransferAmount',
  'historicalFee',
  'historicalReceivedAmount',
  'historicalClientStatus',
  'historicalAdminTransactionId',
  'historicalAdminStatus',
  'adminCandidateCount',
  'approveActionAvailable',
  'approvalClickCount',
  'secondaryConfirmationClickCount',
  'adminStatusBefore',
  'adminStatusAfter',
  'clientLedgerTransactionId',
  'clientLedgerStatus',
  'clientRecordCandidateCount',
  'existingTransferResume',
  'noNewTransferCreated',
  'approvalRemark',
  'approved',
  'submittedStatus',
  'clientFinalStatus',
  'adminFinalStatus',
  'observedStateFlow',
  'clientTransferHistoryRecordCount',
  'clientGlobalLedgerRecordCount',
  'clientGlobalLedgerTransactionIds',
  'clientLedgerTrfSearchSupported',
  'clientGlobalLedgerOracle',
  'actualSourceBalanceDecrease',
  'terminalState',
  'rejectActionAvailable',
  'rejectReasonDisplayed',
  'noNewWithdrawalCreated',
  'dryRun',
  'businessOrderId',
  'quoteValidity',
  'businessId',
  'businessIdSource',
  'transactionId',
  'transactionType',
  'recordOccurredAt',
  'sourceAmountEvidence',
  'transactionStatus',
  'finalStatus',
  'confirmed',
  'potentiallySubmitted',
  'manualCheckRequired',
  'confirmationClicks',
  'securityVerificationClicks',
  'verificationClicked',
  'recordIdsUnchanged',
  'resultSignal',
  'networkObservations',
  'securityKeyDom',
  'registrationStage',
  'adminRegistrationView',
  'registrationLoginIdentity',
  'registrationContactIdentity',
  'registrationTestName',
  'registrationSequence',
  'registrationNameSuffix',
  'registrationNameFieldAccepted',
  'recoverablePreSubmitDisposition',
  'recoverablePreSubmitCorrectionCount',
  'registrationTestNameUnique',
  'registrationEmailAdminPreflight',
  'registrationSignerImplementation',
  'registrationSignerType',
  'registrationDocumentCreated',
  'registrationDocumentOpened',
  'registrationIframeLoaded',
  'registrationFrameUrl',
  'registrationDocumentCreationEvidence',
  'registrationDocumentBelongsToJourney',
  'registrationNoOldDocumentReused',
  'registrationInitialRemainingFields',
  'registrationSignatureFieldLocated',
  'registrationSignatureValue',
  'registrationNamePreserved',
  'registrationTitleStatus',
  'registrationDateStatus',
  'registrationTestSignatureDrawn',
  'registrationSignatureApplied',
  'registrationSignatureMethod',
  'registrationFieldSignClickCount',
  'registrationAgreementActionClickCount',
  'registrationAgreementConfirmationClickCount',
  'registrationFinalRemainingFields',
  'registrationAuthorizationStepCompleted',
  'registrationSigningCompleted',
  'registrationSubmitEnabledBeforeSigning',
  'registrationFinalSubmitClickCount',
  'registrationFinalSubmitAttemptCount',
  'registrationFirstSubmitDiagnostic',
  'registrationRecoverySubmitDiagnostic',
  'registrationRecoveryReloadCount',
  'registrationPostSignFirstSubmitStateDesync',
  'registrationRecoveryDocumentCreationEvidence',
  'registrationFinalSubmitEvidence',
  'registrationSigningStatus',
  'registrationCodeConfigured',
  'registrationDataPoolAvailableCount',
  'registrationProfileConfigured',
  'registrationAccountType',
  'registrationAgreementCount',
  'registrationSubmissionCount',
  'registrationProfileSubmissionCount',
  'registrationTime',
  'clientAuthenticationStatus',
  'clientHomeVerified',
  'personalProfileCompleted',
  'sumsubRequired',
  'authorizationFieldSignClicks',
  'authorizationCompleteClicks',
  'authorizationConfirmationSignClicks',
  'authorizationIdentityChallengePresent',
  'documentOpened',
  'documentIframeLoaded',
  'documentFrameUrl',
  'documentCreationEvidence',
  'documentCreated',
  'documentBelongsToCurrentJourney',
  'noOldDocumentReused',
  'staleDraftDetected',
  'fieldsRemainingBefore',
  'fieldsRemainingAfter',
  'testSignatureDrawn',
  'signatureFieldCompleted',
  'documensoFieldSignCount',
  'completeClickCount',
  'signConfirmClickCount',
  'signClickCount',
  'documensoCompleted',
  'documensoFinalStatus',
  'fidereSigningStatusBefore',
  'fidereSigningStatusAfter',
  'submitEnabledBeforeSigning',
  'submitEnabledAfterSigning',
  'fidereStatusSyncObserved',
  'fidereAutomaticStatusRequestObserved',
  'signingDiagnosticConclusion',
  'registrationFailureCategory',
  'registrationFinalStatus',
  'iframeLoaded',
  'submitGateWarning',
  'finalRegistrationSubmitCount',
  'credentialSource',
  'credentialConfigured',
  'resumeLoginAttemptCount',
  'resumeCredentialAccepted',
  'resumeClientAuthenticated',
  'journeySessionActive',
  'unfinishedKycRestored',
  'documensoDraftAvailable',
  'resumeSigningReady',
  'documentCreationRequestsBlocked',
  'accountCreationStatus',
  'kycSubmissionStatus',
  'documensoCompletionStatus',
  'adminUserCandidateCount',
  'adminUserReference',
  'displayName',
  'adminApproveCount',
  'approvalPreExisted',
  'pendingCandidateCount',
  'candidateSearchMode',
  'adminReviewReference',
  'clientSubmissionStatus',
  'adminFinalState',
  'clientFinalState',
  'resumeEndStage',
  'noNewUserCreated',
  'noRepeatedSigning',
  'noRepeatedUpload',
  'noRepeatedClientSubmission',
  'adminApprovalCompletionEvidence',
  'journeyContextLocation',
  'loginIdentityUnique',
  'contactIdentityUnique',
  'noSecondUserCreated',
  'currentRegistrationStep',
  'uploadedDocumentCount',
  'totalDocumentCount',
  'directorCount',
  'shareholderCount',
  'uboCount',
  'remainingRequiredFields',
  'signingStatus',
  'signingType',
  'initialFields',
  'currentFields',
  'signatureStatus',
  'authorizationStatus'
]);

export function maskEmail(value: string): string {
  return value.replace(
    /([A-Z0-9._%+-]{3})[A-Z0-9._%+-]*(@[^\s@]+)/gi,
    (_match, prefix: string, domain: string) => `${prefix}***${domain}`
  );
}

export function maskBusinessId(value: string): string {
  return value.replace(/\b((?:OTC|TXN|TRF|INV)-)([A-Z0-9]+(?:-[A-Z0-9]+)*)\b/gi, (
    _match,
    prefix: string,
    identifier: string
  ) => {
    const suffix = identifier.replace(/-/g, '').slice(-4);
    return `${prefix}****${suffix}`;
  });
}

export function maskSensitiveText(value: string): string {
  return maskBusinessId(maskEmail(value))
    .replace(/(?<!\d)(1\d{2})\d{4}(\d{4})(?!\d)/g, '$1****$2')
    .replace(/(authorization\s*[:=]\s*)([^\s,;]+)/gi, '$1[已脱敏]')
    .replace(/(bearer\s+)[A-Z0-9._~+/=-]+/gi, '$1[已脱敏]')
    .replace(/((?:password|pwd|otp|captcha|security[_-]?key|token|cookie|secret)\s*[:=]\s*)([^\s,;]+)/gi, '$1[已脱敏]')
    .replace(/\b\d{12,34}\b/g, digits => `****${digits.slice(-4)}`);
}

function sanitizeAllowedValue(value: unknown): unknown {
  if (value === null || typeof value === 'number' || typeof value === 'boolean') {
    return value;
  }

  if (typeof value === 'string') {
    return maskSensitiveText(value);
  }

  if (Array.isArray(value)) {
    return value.map(sanitizeAllowedValue);
  }

  if (typeof value === 'object') {
    const sanitized: Record<string, unknown> = {};

    for (const [key, nestedValue] of Object.entries(value as Record<string, unknown>)) {
      if (!blockedFieldPattern.test(key)) {
        sanitized[key] = sanitizeAllowedValue(nestedValue);
      }
    }

    return sanitized;
  }

  return String(value);
}

export function sanitizeBusinessData(
  data: Record<string, unknown>
): Record<string, unknown> {
  const sanitized: Record<string, unknown> = {};

  for (const [key, value] of Object.entries(data)) {
    if (blockedFieldPattern.test(key) || !allowedBusinessFields.has(key)) {
      continue;
    }

    sanitized[key] = sanitizeAllowedValue(value);
  }

  return sanitized;
}

export function sanitizeRecord<T>(value: T): T {
  if (typeof value === 'string') {
    return maskSensitiveText(value) as T;
  }

  if (Array.isArray(value)) {
    return value.map(item => sanitizeRecord(item)) as T;
  }

  if (value && typeof value === 'object') {
    const output: Record<string, unknown> = {};

    for (const [key, nestedValue] of Object.entries(value as Record<string, unknown>)) {
      output[key] = blockedFieldPattern.test(key)
        ? '[已脱敏]'
        : sanitizeRecord(nestedValue);
    }

    return output as T;
  }

  return value;
}
